title: AbonnementBeheer
modelClass: OpenMindedIT\Omitmanager\Models\SubscriptionManager
list: $/openmindedit/omitmanager/models/subscriptionmanager/columns.yaml
recordUrl: 'openmindedit/omitmanager/abonnementbeheer/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
